# Generated by Django 6.0 on 2026-02-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='action',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='img',
            field=models.ImageField(upload_to='carousel_images/'),
        ),
    ]
