# Generated by Django 6.0 on 2026-02-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_carouselimage_action_carouselimage_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='active',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='caption',
        ),
    ]
