# Generated by Django 6.0 on 2026-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_carouselimage_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='caption',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
