# Generated by Django 6.0 on 2026-01-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(upload_to='product/images/'),
        ),
    ]
