# Generated by Django 6.0 on 2026-02-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_stock_alter_productimage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='products/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(upload_to='products/images/'),
        ),
    ]
